embedding_model: all-MiniLM-L6-v2
rerank_model_name: maidalun1020/bce-reranker-base_v1
ZILLIZ_CLOUD_URI: "https://in03-56a0c941ed0ff6e.serverless.aws-eu-central-1.cloud.zilliz.com"
ZILLIZ_CLOUD_TOKEN: "f0cef636066c8653aa07cf9b435a2faf18dcb7a1e13a19a8c61c11b786f8a49d61c6a7d9d8837844c0b78ace482899432121c9cc"
default_vs_type: milvus
milvus:
  uri: ""
  user: 'root'
  password: ''
chunk_size: 750
overlap_size: 150
top_k: 3
top_n: 1
score_threshold: 0.5
kb_name: 'vulnbot_rag'
search_params: 
  metric_type: "COSINE"
  params: 
    nprobe: 16
index_params: 
  field_name: "embedding"
  index_type: "IVF_FLAT" # Changed from AUTOINDEX
  metric_type: "COSINE"
  params: 
    nlist: 128  # Lower nlist for small datasets
