embedding_model: all-MiniLM-L6-v2
rerank_model_name: maidalun1020/bce-reranker-base_v1
default_vs_type: milvus
milvus:
  uri: ""
  user: 'root'
  password: ''
chunk_size: 750
overlap_size: 150
top_k: 3
top_n: 1
score_threshold: 0.5
kb_name: 'vulcan_rag'
search_params: 
  metric_type: "COSINE"
  params: 
    nprobe: 16
index_params: 
  field_name: "embedding"
  index_type: "IVF_FLAT" # Changed from AUTOINDEX
  metric_type: "COSINE"
  params: 
    nlist: 128  # Lower nlist for small datasets
