server: mistral
aws_region: us-east-1
bedrock_model_id: us.anthropic.claude-sonnet-4-20250514-v1:0
ollama_host: "https://b863ebd427dd.ngrok-free.app"
ollama_model_id: gpt-oss:latest
ollama_embedding_model_id: mxbai-embed-large
mistral_api_key: ${MISTRAL_API_KEY}
mistral_model_id: mistral-large-latest
openai_api_key: ${OPENAI_API_KEY}
openai_model_id: "gpt-4o"
openai_base_url: "" 
gemini_api_key: ${GEMINI_API_KEY} 
gemini_model_id: "gemini/gemini-1.5-pro"
temperature: 0.5
history_len: 10
max_tokens: 4096
timeout: 600
