server: remote  
aws_region: us-east-1
bedrock_model_id: us.anthropic.claude-sonnet-4-20250514-v1:0
ollama_host: https://10fe41ebe151.ngrok-free.app
ollama_model_id: gpt-oss:latest
ollama_embedding_model_id: mxbai-embed-large
temperature: 0.5
history_len: 10
timeout: 600
